# mysql 5  驱动不同 com.mysql.jdbc.Driver
# mysql 8  驱动不同 com.mysql.cj.jdbc.Driver、需要增加时区的配置serverTimezone=GMT%2B8
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

